server:
  port: 8088
  
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false #关闭缓存
    check-template-location: true
    servlet:
      content-type: text/html
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autotestdb
    username: autotest
    password: auto123456
# mybatis配置
mybatis:
  #mapper配置文件所在位置
  mapper-locations: classpath:mapper/*.xml
  #实体所在的包
  type-aliases-package: com.crc.bean
  # 驼峰原则
  configuration:
    map-underscore-to-camel-case: true

  
  
  
#spring:
 # datasource:
  #  name: autotestdb
   # type: com.alibaba.druid.pool.DruidDataSource
   # driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/autotestdb?characterEncoding=UTF-8&useUnicode=true
    #url: jdbc\:mysql\://127.0.0.1\:3306/autotestdb
    #username: autotest
    #password: auto123456
    #filters: stat
    #maxActive: 20
    #initialSize: 1
    #maxWait: 60000
    #minIdle: 1
    #timeBetweenEvictionRunsMillis: 60000
    #minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    #testWhileIdle: true
    #testOnBorrow: false
    #testOnReturn: false
   # poolPreparedStatements: true
    #maxOpenPreparedStatements: 20

 # mybatis:
  #  typeAliasesPackage: com.crc.bean  
   # mapperLocations: classpath:mapper/*.xml 
 # frameworker:
 #   template-loader-path: classpath:/templates/
 #   cache: false
 #   charset: UTF-8
 #   check-template-location: true
 #   content-type: text/html
 #   expose-request-attributes: true
 #   expose-session-attributes: true
 #   request-context-attributes: request
  #  suffix: .crc
    

  
#pagehelper:
  #helperDialect: mysql
 # reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
  